Repository Ansible2/Arma-3-Survival, pull requests merged in 2021-03, with the labels that each got.

#345 Added a merged RHS faction, named RHS ALL, that include all RHS unit
  Headers/descriptionEXT/Faction Headers/Define Factions.hpp
  Headers/descriptionEXT/Faction Headers/Faction Master.hpp
  Headers/descriptionEXT/Faction Headers/RHS ALL.hpp
Labels: test required

#401 Fix #400 : Passive helicopter support does not follow speed limit
  Functions/Supports/fn_passiveHelicopterGunner.sqf
Labels: MASTER Build, bug

#402 Delete Aegis Atlas Opposing Forces Unit Table.hpp (Delete #378)
  Headers/descriptionEXT/Faction Headers/Aegis Atlas Opposing Forces Unit Table.hpp
Labels: documentation

#403 Fix #396 : Overrun wave rebalance
  Functions/Init Functions/fn_playAreaEnforcementLoop.sqf
  Functions/Init Functions/fn_prepareGlobals.sqf
  Functions/Stalking/fn_stopStalking.sqf
  Functions/Supports/fn_aircraftGunner.sqf
  Functions/Wave Type Libraries/Overrun Wave Library/fn_handleOverrunWave.sqf
  Functions/Wave Type Libraries/Overrun Wave Library/fn_overrunTheCrateWave.sqf
  Functions/Waves/fn_decideWaveType.sqf
  Headers/String Constants.hpp
  initPlayerLocal.sqf
Labels: enhancement

#405 Fixes for #404 : Remove old files
  Functions/Init Functions/fn_initClientAlias.sqf
  Functions/Init Functions/fn_initServerAlias.sqf
  Functions/Init Functions/fn_keepPlayerInGroup.sqf
  Functions/Other/testFSM.fsm
  Functions/Parameter Saving/fn_getSavedParamIndex.sqf
  Functions/Parameter Saving/fn_getSavedParamValue.sqf
  Functions/Parameter Saving/fn_saveAllMissionParameters.sqf
  Functions/Parameter Saving/fn_setParam.sqf
  Headers/descriptionEXT/functions.hpp
Labels: enhancement

#407 Fix for #406 : Satellite shops can still be bought by JIP players
  Functions/Init Functions/fn_prepareGlobals.sqf
Labels: MASTER Build, bug

#408 Changes for #394 & #397
  Functions/Other/fn_handleWaitingForReviveEvent.sqf
  Functions/Waves/fn_decideWaveType.sqf
Labels: MASTER Build, bug
