Repository Ansible2/Arma-3-Survival, pull requests merged in 2021-05, with the labels that each got.

#481 Update From Working branch
  Functions/Build/fn_buildEvent_onPickedUp.sqf
  Functions/Build/fn_buildEvent_onPlaced.sqf
  Functions/Build/fn_buildEvent_onPurchasedPostNetwork.sqf
  Functions/Build/fn_buildEvent_onPurchasedPostfix.sqf
  Functions/Build/fn_buildEvent_onSold.sqf
  Functions/Init Functions/fn_prepareGlobals.sqf
  Functions/Supports/fn_callingForSupportMaster.sqf
  Functions/Unique Build Item Libraries/Satellite Shop/fn_satelliteShop_init.sqf
  Functions/Unique Build Item Libraries/Satellite Shop/fn_satelliteShop_preparePlayer.sqf
  Functions/Waves/fn_decideWaveType.sqf
  Functions/build/fn_purchaseObject.sqf
  Headers/descriptionEXT/Faction Headers/Define Factions.hpp
  Headers/descriptionEXT/Faction Headers/Faction Master.hpp
  Headers/descriptionEXT/Faction Headers/SOGPF Unit Table.hpp
  Headers/descriptionEXT/Faction Headers/Vanilla Unit Table.hpp
  Headers/descriptionEXT/missionParams.hpp
  KISKA Systems/KISKA Functions.hpp
  KISKA Systems/KISKA Utility Functions/fn_detectControlKeys.sqf
Labels: bug, documentation, enhancement

#476 Adding There is Only War mod support
  Headers/descriptionEXT/Faction Headers/Define Factions.hpp
  Headers/descriptionEXT/Faction Headers/Faction Master.hpp
  Headers/descriptionEXT/Faction Headers/There is Only War AM Unit Table.hpp
  Headers/descriptionEXT/Faction Headers/There is Only War Chaos Unit Table.hpp
  Headers/descriptionEXT/Faction Headers/There is Only War SM Unit Table.hpp
  Headers/descriptionEXT/Faction Headers/There is Only War Xenos Unit Table.hpp
Labels: documentation

#478 Add Suicide Bomber Vest
  Functions/Wave Type Libraries/Suicide Wave Library/fn_createSuicideWave.sqf
Labels: enhancement

#482 Finished SOG PF Factions and Added Supports
  Functions/CBAP/fn_vectDir.sqf
  Functions/Supports/fn_aircraftGunner.sqf
  Functions/Supports/fn_callingForSupportMaster.sqf
  Headers/descriptionEXT/Build Items/Main Build Items.hpp
  Headers/descriptionEXT/Faction Headers/Define Factions.hpp
  Headers/descriptionEXT/Faction Headers/SOGPF Unit Table.hpp
  Headers/descriptionEXT/functions.hpp
  Headers/descriptionEXT/supportDefines.hpp
  Headers/descriptionEXT/supports.hpp
  KISKA Systems/KISKA Utility Functions/fn_CAS.sqf
Labels: documentation, enhancement

#485 Add loot limit and removed deletion of loot holders every wave
  Functions/Init Functions/fn_prepareGlobals.sqf
  Functions/Supports/fn_createLootMarkers.sqf
  Functions/Waves/fn_spawnLoot.sqf
  Functions/Waves/fn_startWave.sqf
  Headers/descriptionEXT/missionParams.hpp
Labels: enhancement

#487 Finished SOG PF Item Implementation
  Functions/Init Functions/fn_createBuildObjectsHash.sqf
  Headers/descriptionEXT/Build Items/Main Build Items.hpp
  Headers/descriptionEXT/Build Items/SOG PF Build Items.hpp
  Headers/descriptionEXT/GUI/shopGUICommonDefines.hpp
Labels: documentation

#498 Added custom loot list presets
  Functions/Init Functions/fn_prepareGlobals.sqf
  Functions/Init Functions/fn_prepareLootClasses.sqf
  Headers/descriptionEXT/Loot Lists.hpp
  Headers/descriptionEXT/Loot Lists/Define Loot Lists.hpp
  Headers/descriptionEXT/Loot Lists/Main Loot List.hpp
  Headers/descriptionEXT/Loot Lists/SOG PF Loot List.hpp
  Headers/descriptionEXT/missionParams.hpp
  description.ext
Labels: documentation, enhancement
