Repository Ansible2/Arma-3-Survival, pull requests merged in 2021-04, with the labels that each got.

#426 Fixes for #420 : Invincible items are still able to be destroyed
  Functions/build/fn_purchaseObject.sqf
Labels: MASTER Build, bug

#431 Fixes for #430 : Playlist save and delete affected incorrect list entry
  Functions/Music Manager/fn_musicManagerOnLoad_deleteButton.sqf
  Functions/Music Manager/fn_musicManagerOnload_savePlaylistControls.sqf
Labels: MASTER Build, bug

#432 Fix for #429 : Loaded playlists in Music Manager are directly loaded into the current playlist
  Functions/Music Manager/fn_musicManagerOnload_savePlaylistControls.sqf
Labels: bug

#434 Added #416 : Coloring for music manager
  Functions/Music Manager/fn_musicManagerOnLoad_loadControls.sqf
  Functions/Music Manager/fn_musicManagerOnload.sqf
  Functions/Music Manager/fn_musicManagerOnload_addAndRemoveButtons.sqf
  Functions/Music Manager/fn_musicManagerOnload_availableMusicList.sqf
  Functions/Music Manager/fn_musicManager_adjustNameColor.sqf
  Headers/descriptionEXT/functions.hpp
Labels: MASTER Build, bug

#435 General cleaning for Music Manager functions
  Functions/Music Manager/fn_musicManagerOnLoad_commitButton.sqf
  Functions/Music Manager/fn_musicManagerOnLoad_deleteButton.sqf
  Functions/Music Manager/fn_musicManagerOnLoad_loadControls.sqf
  Functions/Music Manager/fn_musicManagerOnload_closeButton.sqf
  Functions/Music Manager/fn_musicManagerOnload_currentPlaylistLoop.sqf
  Functions/Music Manager/fn_musicManagerOnload_pauseAndPlayButtons.sqf
  Functions/Music Manager/fn_musicManagerOnload_savePlaylistControls.sqf
  Functions/Music Manager/fn_musicManagerOnload_systemOnOffCombo.sqf
  Functions/Music Manager/fn_musicManagerOnload_timelineSlider.sqf
  Functions/Music Manager/fn_musicManagerOnload_trackSpacingControls.sqf
  Functions/Music Manager/fn_musicManagerOnload_volumeSlider.sqf
  Functions/Music Manager/fn_musicManager_playMusic.sqf
  Functions/Music Manager/fn_musicManager_setPlaylistServer.sqf
Labels: enhancement

#436 Fix for #433 : timeline slider in Music Manager not scaling properly
  Functions/Music Manager/fn_musicManagerOnload.sqf
  Functions/Music Manager/fn_musicManager_playMusic.sqf
Labels: bug

#438 Fix for #437 : Loot blacklist not working
  Functions/Init Functions/fn_prepareLootClasses.sqf
  Functions/Waves/fn_spawnLoot.sqf
Labels: bug

#410 Added ability to change the time speed multiplier from the parameters window
  Functions/Init Functions/fn_prepareGlobals.sqf
  Functions/Wave Type Libraries/Twelve Hour Wave Library/fn_handleTwelveHourWave.sqf
  Functions/Waves/fn_decideWaveType.sqf
  Headers/String Constants.hpp
  Headers/descriptionEXT/functions.hpp
  Headers/descriptionEXT/missionParams.hpp
  initServer.sqf
Labels: enhancement

#440 Fix for #419 : VDL system was not turned off when entering gunner support
  Functions/Supports/fn_aircraftGunner.sqf
Labels: bug

#444 Add helicopter special wave
  Functions/Init Functions/fn_prepareGlobals.sqf
  Functions/Supports/fn_aircraftGunner.sqf
  Functions/Supports/fn_passiveHelicopterGunner.sqf
  Functions/Wave Type Libraries/Helicopter Wave Library/fn_handleHelicopterWave.sqf
  Functions/Wave Type Libraries/Standard Wave Library/fn_stdEnemyVehicles.sqf
  Functions/Waves/fn_decideWaveType.sqf
  Headers/String Constants.hpp
  Headers/descriptionEXT/functions.hpp
  Headers/descriptionEXT/missionParams.hpp
  KISKA Systems/KISKA Functions.hpp
  KISKA Systems/KISKA Utility Functions/fn_classTurretsWithGuns.sqf
Labels: enhancement

#425 Added Max Terminator factions to the game mode
  Headers/descriptionEXT/Faction Headers/Define Factions.hpp
  Headers/descriptionEXT/Faction Headers/Faction Master.hpp
  Headers/descriptionEXT/Faction Headers/Max Terminator.hpp
Labels: documentation

#461 Update loot marker network interaction
  Functions/Other Actions/fn_addRevealLootAction.sqf
  Functions/Other/fn_lootReveal.sqf
  Functions/Supports/fn_createLootMarkers.sqf
  Functions/Waves/fn_spawnLoot.sqf
  Headers/Loot Reveal Types.hpp
  Headers/descriptionEXT/functions.hpp
Labels: bug, enhancement

#465 Completed update of paratrooper wave functions
  Functions/Supports/fn_arsenalSupplyDrop.sqf
  Functions/Supports/fn_callingForSupportMaster.sqf
  Functions/Supports/fn_daisyCutter.sqf
  Functions/Wave Type Libraries/Paratrooper Wave Library/fn_handleParatrooperWave.sqf
  Headers/descriptionEXT/functions.hpp
  KISKA Systems/KISKA Functions.hpp
  KISKA Systems/KISKA Utility Functions/fn_CAS.sqf
  KISKA Systems/KISKA Utility Functions/fn_paratroopers.sqf
  KISKA Systems/KISKA Utility Functions/fn_spawnVehicle.sqf
  KISKA Systems/KISKA Utility Functions/fn_staticLine.sqf
Labels: enhancement
